apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: server
  namespace: monitoring
  labels:
    app.kubernetes.io/name: prometheus-server
    app.kubernetes.io/version: 0.74.0
spec:
  enableFeatures:
    - exemplar-storage
  replicas: 1
  enableAdminAPI: false
  evaluationInterval: 30s
  externalLabels:
    environment: development
  externalUrl: http://prometheus-server.monitoring:9090
  hostNetwork: false
  listenLocal: false
  logFormat: logfmt
  logLevel: info
  paused: false
  podMonitorNamespaceSelector: {}
  podMonitorSelector: {}
  portName: http-web
  probeNamespaceSelector: {}
  probeSelector: {}
  retention: 10d
  routePrefix: /
  ruleNamespaceSelector: {}
  ruleSelector: {}
  scrapeInterval: 1m
  scrapeTimeout: 30s
  securityContext:
    fsGroup: 2000
    runAsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: prometheus
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}
  shards: 1
  tsdb:
    outOfOrderTimeWindow: 0s
  walCompression: true
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: prometheus-server
    app.kubernetes.io/version: 0.74.0
  name: prometheus-server
  namespace: monitoring
spec:
  ports:
    - name: http
      port: 9090
      targetPort: http-web
  selector:
    app.kubernetes.io/name: prometheus
