apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-setup-check-config
  namespace: default
  labels:
    app: k8s-setup-check-config
data:
  # BASE
  GIN_MODE: "release"
  ENVIRONMENT: "production"
  SERVICE_NAME: "demoservice"
  SERVICE_VERSION: "1.0"
  OTLP_SERVER_URL: "tempo.monitoring:4318"
